
version: 0.1
phases:
  install:
    commands:
      - cd hello_world && npm install
      - aws cloudformation package --template-file template.yaml --s3-bucket samlambda --output-template-file outputSamTemplate.yaml
                                   
artifacts:
  type: zip
  files:
    - template.yaml
    - outputSamTemplate.yaml
